<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            ADMIN POGLED:<br />
            <br />
            Prijava: <asp:TextBox ID="txtBPrijava" runat="server"></asp:TextBox>
            <br />
            <br />
            Geslo: <asp:TextBox ID="txtBGeslo" runat="server"></asp:TextBox>
            <br />
            <asp:Button ID="bttPrijava" runat="server" Text="Prijava" Width="181px" OnClick="bttPrijava_Click" />
            <br />
        </div>
        <div>


            Admin pogled:&nbsp; 
            <asp:Button ID="bttIzpisVsehOseb" runat="server" Enabled="False" OnClick="bttIzpisVsehOseb_Click" Text="Vse Osebe" />
            <asp:Button ID="bttVsaPodjetja" runat="server" Enabled="False" OnClick="bttVsaPodjetja_Click" Text="Vsa Podjetja" />
            <asp:Button ID="bttDodajOseboVPodjetje" runat="server" OnClick="bttDodajOseboVPodjetje_Click" Text="Dodaj Osebo v Podjetje" Enabled="False" />
            <asp:Button ID="bttOdstraniOseboIzPodjetja" runat="server" Enabled="False" OnClick="bttOdstraniOseboIzPodjetja_Click" Text="Odstani osebo iz podjetja" />
            <asp:Button ID="bttUrediOsebo" runat="server" Enabled="False" OnClick="bttUrediOsebo_Click" Text="Uredi osebo" />
            <asp:Button ID="bttUrediPodjetje" runat="server" Enabled="False" OnClick="bttUrediPodjetje_Click" Text="Uredi Podjetje" />
            <br />
            <br />
            Pogledi:&nbsp; 
            <asp:Button ID="bttOsebeVPod" runat="server" OnClick="bttOsebeVPod_Click" Text="Izpis oseb v podjetju" />
            <asp:Button ID="bttvseosebePodjetje" runat="server" Text="Vsa podjetja osebe" OnClick="bttvseosebePodjetje_Click" />


            <asp:Button ID="bttOsebaPodrobnosti" runat="server" OnClick="bttOsebaPodrobnosti_Click" Text="Podrobnosti osebe" />


        </div>
        <div>

            <asp:GridView ID="GridView1" runat="server" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting">
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <br />
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>

        </div>
        <div id="izberiPodjetje">

            <br />
            Izberi Podjetje:<asp:GridView ID="GridViewPodjetje" runat="server" AutoGenerateSelectButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" Enabled="False" ForeColor="Black" OnSelectedIndexChanging="GridView2_SelectedIndexChanging" OnRowEditing="GridViewPodjetje_RowEditing">
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

        </div>
        <div>

            Izberi Osebo:<br />
            <asp:GridView ID="GridViewOseba" runat="server" AutoGenerateSelectButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" Enabled="False" ForeColor="Black" OnSelectedIndexChanging="GridViewOseba_SelectedIndexChanging">
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <br />

        </div>
        <div>

            Vnesi delovno mesto: <asp:TextBox ID="txtBDelovnoMesto" runat="server" Enabled="False"></asp:TextBox>
            <br />
            Vnesi datum do: <asp:TextBox ID="txtBDatumDo" runat="server" Enabled="False"></asp:TextBox>

        </div>
    </form>
</body>
</html>
