//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.27130.2010
// 
namespace UWP.ServiceReference2 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLetalisceByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<UWP.ServiceReference2.GetLetalisceByCodeResponse> GetLetalisceByCodeAsync(UWP.ServiceReference2.GetLetalisceByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeltalisceDrzava", ReplyAction="*")]
        System.Threading.Tasks.Task<UWP.ServiceReference2.GetLeltalisceDrzavaResponse> GetLeltalisceDrzavaAsync(UWP.ServiceReference2.GetLeltalisceDrzavaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLetalisceByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLetalisceByCode", Namespace="http://tempuri.org/", Order=0)]
        public UWP.ServiceReference2.GetLetalisceByCodeRequestBody Body;
        
        public GetLetalisceByCodeRequest() {
        }
        
        public GetLetalisceByCodeRequest(UWP.ServiceReference2.GetLetalisceByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLetalisceByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public GetLetalisceByCodeRequestBody() {
        }
        
        public GetLetalisceByCodeRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLetalisceByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLetalisceByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public UWP.ServiceReference2.GetLetalisceByCodeResponseBody Body;
        
        public GetLetalisceByCodeResponse() {
        }
        
        public GetLetalisceByCodeResponse(UWP.ServiceReference2.GetLetalisceByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLetalisceByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLetalisceByCodeResult;
        
        public GetLetalisceByCodeResponseBody() {
        }
        
        public GetLetalisceByCodeResponseBody(string GetLetalisceByCodeResult) {
            this.GetLetalisceByCodeResult = GetLetalisceByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLeltalisceDrzavaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLeltalisceDrzava", Namespace="http://tempuri.org/", Order=0)]
        public UWP.ServiceReference2.GetLeltalisceDrzavaRequestBody Body;
        
        public GetLeltalisceDrzavaRequest() {
        }
        
        public GetLeltalisceDrzavaRequest(UWP.ServiceReference2.GetLeltalisceDrzavaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLeltalisceDrzavaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drzava;
        
        public GetLeltalisceDrzavaRequestBody() {
        }
        
        public GetLeltalisceDrzavaRequestBody(string drzava) {
            this.drzava = drzava;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLeltalisceDrzavaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLeltalisceDrzavaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UWP.ServiceReference2.GetLeltalisceDrzavaResponseBody Body;
        
        public GetLeltalisceDrzavaResponse() {
        }
        
        public GetLeltalisceDrzavaResponse(UWP.ServiceReference2.GetLeltalisceDrzavaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLeltalisceDrzavaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UWP.ServiceReference2.ArrayOfString GetLeltalisceDrzavaResult;
        
        public GetLeltalisceDrzavaResponseBody() {
        }
        
        public GetLeltalisceDrzavaResponseBody(UWP.ServiceReference2.ArrayOfString GetLeltalisceDrzavaResult) {
            this.GetLeltalisceDrzavaResult = GetLeltalisceDrzavaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : UWP.ServiceReference2.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<UWP.ServiceReference2.WebServiceSoap>, UWP.ServiceReference2.WebServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient() : 
                base(WebServiceSoapClient.GetDefaultBinding(), WebServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.WebServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UWP.ServiceReference2.GetLetalisceByCodeResponse> UWP.ServiceReference2.WebServiceSoap.GetLetalisceByCodeAsync(UWP.ServiceReference2.GetLetalisceByCodeRequest request) {
            return base.Channel.GetLetalisceByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<UWP.ServiceReference2.GetLetalisceByCodeResponse> GetLetalisceByCodeAsync(string code) {
            UWP.ServiceReference2.GetLetalisceByCodeRequest inValue = new UWP.ServiceReference2.GetLetalisceByCodeRequest();
            inValue.Body = new UWP.ServiceReference2.GetLetalisceByCodeRequestBody();
            inValue.Body.code = code;
            return ((UWP.ServiceReference2.WebServiceSoap)(this)).GetLetalisceByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UWP.ServiceReference2.GetLeltalisceDrzavaResponse> UWP.ServiceReference2.WebServiceSoap.GetLeltalisceDrzavaAsync(UWP.ServiceReference2.GetLeltalisceDrzavaRequest request) {
            return base.Channel.GetLeltalisceDrzavaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UWP.ServiceReference2.GetLeltalisceDrzavaResponse> GetLeltalisceDrzavaAsync(string drzava) {
            UWP.ServiceReference2.GetLeltalisceDrzavaRequest inValue = new UWP.ServiceReference2.GetLeltalisceDrzavaRequest();
            inValue.Body = new UWP.ServiceReference2.GetLeltalisceDrzavaRequestBody();
            inValue.Body.drzava = drzava;
            return ((UWP.ServiceReference2.WebServiceSoap)(this)).GetLeltalisceDrzavaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:58950/WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return WebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.WebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return WebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.WebServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            WebServiceSoap,
        }
    }
}
