//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WpfApp.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StoritveIzpitiSoap", Namespace="http://tempuri.org/")]
    public partial class StoritveIzpiti : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPodjetjeMaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebeVPodOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebaImeOperationCompleted;
        
        private System.Threading.SendOrPostCallback minOsebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaOsebOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaPodjetjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback povprecnaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebeAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPodjetjeAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback isAdministratorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPodjetjeWithMaxOsebOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebaWithMaxPodOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNewOsebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNewPodjetjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveOsebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemovePodjetjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOsebaVPodjetjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveOsebeIzPodjetjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOsebeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePodjetjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback OdstraniOseboOperationCompleted;
        
        private System.Threading.SendOrPostCallback OdstraniPodjetjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback OdstraniOseboIzPodjetjaByIndexOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOsebaVPodjetjeByIndexOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StoritveIzpiti() {
            this.Url = global::WpfApp.Properties.Settings.Default.WpfApp_localhost_StoritveIzpiti;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPodjetjeMaxCompletedEventHandler getPodjetjeMaxCompleted;
        
        /// <remarks/>
        public event getOsebeVPodCompletedEventHandler getOsebeVPodCompleted;
        
        /// <remarks/>
        public event getOsebaImeCompletedEventHandler getOsebaImeCompleted;
        
        /// <remarks/>
        public event minOsebaCompletedEventHandler minOsebaCompleted;
        
        /// <remarks/>
        public event listaOsebCompletedEventHandler listaOsebCompleted;
        
        /// <remarks/>
        public event listaPodjetjaCompletedEventHandler listaPodjetjaCompleted;
        
        /// <remarks/>
        public event povprecnaCompletedEventHandler povprecnaCompleted;
        
        /// <remarks/>
        public event getOsebeAllCompletedEventHandler getOsebeAllCompleted;
        
        /// <remarks/>
        public event getPodjetjeAllCompletedEventHandler getPodjetjeAllCompleted;
        
        /// <remarks/>
        public event isAdministratorCompletedEventHandler isAdministratorCompleted;
        
        /// <remarks/>
        public event getPodjetjeWithMaxOsebCompletedEventHandler getPodjetjeWithMaxOsebCompleted;
        
        /// <remarks/>
        public event getOsebaWithMaxPodCompletedEventHandler getOsebaWithMaxPodCompleted;
        
        /// <remarks/>
        public event InsertNewOsebaCompletedEventHandler InsertNewOsebaCompleted;
        
        /// <remarks/>
        public event InsertNewPodjetjeCompletedEventHandler InsertNewPodjetjeCompleted;
        
        /// <remarks/>
        public event InsertNewUserCompletedEventHandler InsertNewUserCompleted;
        
        /// <remarks/>
        public event RemoveOsebaCompletedEventHandler RemoveOsebaCompleted;
        
        /// <remarks/>
        public event RemovePodjetjeCompletedEventHandler RemovePodjetjeCompleted;
        
        /// <remarks/>
        public event AddOsebaVPodjetjeCompletedEventHandler AddOsebaVPodjetjeCompleted;
        
        /// <remarks/>
        public event RemoveOsebeIzPodjetjaCompletedEventHandler RemoveOsebeIzPodjetjaCompleted;
        
        /// <remarks/>
        public event UpdateOsebeCompletedEventHandler UpdateOsebeCompleted;
        
        /// <remarks/>
        public event UpdatePodjetjeCompletedEventHandler UpdatePodjetjeCompleted;
        
        /// <remarks/>
        public event OdstraniOseboCompletedEventHandler OdstraniOseboCompleted;
        
        /// <remarks/>
        public event OdstraniPodjetjeCompletedEventHandler OdstraniPodjetjeCompleted;
        
        /// <remarks/>
        public event OdstraniOseboIzPodjetjaByIndexCompletedEventHandler OdstraniOseboIzPodjetjaByIndexCompleted;
        
        /// <remarks/>
        public event AddOsebaVPodjetjeByIndexCompletedEventHandler AddOsebaVPodjetjeByIndexCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPodjetjeMax", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OsebaVPodjetju getPodjetjeMax(string pod) {
            object[] results = this.Invoke("getPodjetjeMax", new object[] {
                        pod});
            return ((OsebaVPodjetju)(results[0]));
        }
        
        /// <remarks/>
        public void getPodjetjeMaxAsync(string pod) {
            this.getPodjetjeMaxAsync(pod, null);
        }
        
        /// <remarks/>
        public void getPodjetjeMaxAsync(string pod, object userState) {
            if ((this.getPodjetjeMaxOperationCompleted == null)) {
                this.getPodjetjeMaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPodjetjeMaxOperationCompleted);
            }
            this.InvokeAsync("getPodjetjeMax", new object[] {
                        pod}, this.getPodjetjeMaxOperationCompleted, userState);
        }
        
        private void OngetPodjetjeMaxOperationCompleted(object arg) {
            if ((this.getPodjetjeMaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPodjetjeMaxCompleted(this, new getPodjetjeMaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebeVPod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba[] getOsebeVPod() {
            object[] results = this.Invoke("getOsebeVPod", new object[0]);
            return ((Oseba[])(results[0]));
        }
        
        /// <remarks/>
        public void getOsebeVPodAsync() {
            this.getOsebeVPodAsync(null);
        }
        
        /// <remarks/>
        public void getOsebeVPodAsync(object userState) {
            if ((this.getOsebeVPodOperationCompleted == null)) {
                this.getOsebeVPodOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebeVPodOperationCompleted);
            }
            this.InvokeAsync("getOsebeVPod", new object[0], this.getOsebeVPodOperationCompleted, userState);
        }
        
        private void OngetOsebeVPodOperationCompleted(object arg) {
            if ((this.getOsebeVPodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebeVPodCompleted(this, new getOsebeVPodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebaIme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba getOsebaIme(string vnesenoIme) {
            object[] results = this.Invoke("getOsebaIme", new object[] {
                        vnesenoIme});
            return ((Oseba)(results[0]));
        }
        
        /// <remarks/>
        public void getOsebaImeAsync(string vnesenoIme) {
            this.getOsebaImeAsync(vnesenoIme, null);
        }
        
        /// <remarks/>
        public void getOsebaImeAsync(string vnesenoIme, object userState) {
            if ((this.getOsebaImeOperationCompleted == null)) {
                this.getOsebaImeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebaImeOperationCompleted);
            }
            this.InvokeAsync("getOsebaIme", new object[] {
                        vnesenoIme}, this.getOsebaImeOperationCompleted, userState);
        }
        
        private void OngetOsebaImeOperationCompleted(object arg) {
            if ((this.getOsebaImeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebaImeCompleted(this, new getOsebaImeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/minOseba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba minOseba() {
            object[] results = this.Invoke("minOseba", new object[0]);
            return ((Oseba)(results[0]));
        }
        
        /// <remarks/>
        public void minOsebaAsync() {
            this.minOsebaAsync(null);
        }
        
        /// <remarks/>
        public void minOsebaAsync(object userState) {
            if ((this.minOsebaOperationCompleted == null)) {
                this.minOsebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnminOsebaOperationCompleted);
            }
            this.InvokeAsync("minOseba", new object[0], this.minOsebaOperationCompleted, userState);
        }
        
        private void OnminOsebaOperationCompleted(object arg) {
            if ((this.minOsebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.minOsebaCompleted(this, new minOsebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaOseb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba[] listaOseb(string imePod) {
            object[] results = this.Invoke("listaOseb", new object[] {
                        imePod});
            return ((Oseba[])(results[0]));
        }
        
        /// <remarks/>
        public void listaOsebAsync(string imePod) {
            this.listaOsebAsync(imePod, null);
        }
        
        /// <remarks/>
        public void listaOsebAsync(string imePod, object userState) {
            if ((this.listaOsebOperationCompleted == null)) {
                this.listaOsebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaOsebOperationCompleted);
            }
            this.InvokeAsync("listaOseb", new object[] {
                        imePod}, this.listaOsebOperationCompleted, userState);
        }
        
        private void OnlistaOsebOperationCompleted(object arg) {
            if ((this.listaOsebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaOsebCompleted(this, new listaOsebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaPodjetja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Podjetje[] listaPodjetja(string imeOsebe) {
            object[] results = this.Invoke("listaPodjetja", new object[] {
                        imeOsebe});
            return ((Podjetje[])(results[0]));
        }
        
        /// <remarks/>
        public void listaPodjetjaAsync(string imeOsebe) {
            this.listaPodjetjaAsync(imeOsebe, null);
        }
        
        /// <remarks/>
        public void listaPodjetjaAsync(string imeOsebe, object userState) {
            if ((this.listaPodjetjaOperationCompleted == null)) {
                this.listaPodjetjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaPodjetjaOperationCompleted);
            }
            this.InvokeAsync("listaPodjetja", new object[] {
                        imeOsebe}, this.listaPodjetjaOperationCompleted, userState);
        }
        
        private void OnlistaPodjetjaOperationCompleted(object arg) {
            if ((this.listaPodjetjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaPodjetjaCompleted(this, new listaPodjetjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/povprecna", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string povprecna() {
            object[] results = this.Invoke("povprecna", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void povprecnaAsync() {
            this.povprecnaAsync(null);
        }
        
        /// <remarks/>
        public void povprecnaAsync(object userState) {
            if ((this.povprecnaOperationCompleted == null)) {
                this.povprecnaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpovprecnaOperationCompleted);
            }
            this.InvokeAsync("povprecna", new object[0], this.povprecnaOperationCompleted, userState);
        }
        
        private void OnpovprecnaOperationCompleted(object arg) {
            if ((this.povprecnaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.povprecnaCompleted(this, new povprecnaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebeAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba[] getOsebeAll() {
            object[] results = this.Invoke("getOsebeAll", new object[0]);
            return ((Oseba[])(results[0]));
        }
        
        /// <remarks/>
        public void getOsebeAllAsync() {
            this.getOsebeAllAsync(null);
        }
        
        /// <remarks/>
        public void getOsebeAllAsync(object userState) {
            if ((this.getOsebeAllOperationCompleted == null)) {
                this.getOsebeAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebeAllOperationCompleted);
            }
            this.InvokeAsync("getOsebeAll", new object[0], this.getOsebeAllOperationCompleted, userState);
        }
        
        private void OngetOsebeAllOperationCompleted(object arg) {
            if ((this.getOsebeAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebeAllCompleted(this, new getOsebeAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPodjetjeAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Podjetje[] getPodjetjeAll() {
            object[] results = this.Invoke("getPodjetjeAll", new object[0]);
            return ((Podjetje[])(results[0]));
        }
        
        /// <remarks/>
        public void getPodjetjeAllAsync() {
            this.getPodjetjeAllAsync(null);
        }
        
        /// <remarks/>
        public void getPodjetjeAllAsync(object userState) {
            if ((this.getPodjetjeAllOperationCompleted == null)) {
                this.getPodjetjeAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPodjetjeAllOperationCompleted);
            }
            this.InvokeAsync("getPodjetjeAll", new object[0], this.getPodjetjeAllOperationCompleted, userState);
        }
        
        private void OngetPodjetjeAllOperationCompleted(object arg) {
            if ((this.getPodjetjeAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPodjetjeAllCompleted(this, new getPodjetjeAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isAdministrator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool isAdministrator(string rac, string geslo) {
            object[] results = this.Invoke("isAdministrator", new object[] {
                        rac,
                        geslo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isAdministratorAsync(string rac, string geslo) {
            this.isAdministratorAsync(rac, geslo, null);
        }
        
        /// <remarks/>
        public void isAdministratorAsync(string rac, string geslo, object userState) {
            if ((this.isAdministratorOperationCompleted == null)) {
                this.isAdministratorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisAdministratorOperationCompleted);
            }
            this.InvokeAsync("isAdministrator", new object[] {
                        rac,
                        geslo}, this.isAdministratorOperationCompleted, userState);
        }
        
        private void OnisAdministratorOperationCompleted(object arg) {
            if ((this.isAdministratorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isAdministratorCompleted(this, new isAdministratorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPodjetjeWithMaxOseb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Podjetje getPodjetjeWithMaxOseb() {
            object[] results = this.Invoke("getPodjetjeWithMaxOseb", new object[0]);
            return ((Podjetje)(results[0]));
        }
        
        /// <remarks/>
        public void getPodjetjeWithMaxOsebAsync() {
            this.getPodjetjeWithMaxOsebAsync(null);
        }
        
        /// <remarks/>
        public void getPodjetjeWithMaxOsebAsync(object userState) {
            if ((this.getPodjetjeWithMaxOsebOperationCompleted == null)) {
                this.getPodjetjeWithMaxOsebOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPodjetjeWithMaxOsebOperationCompleted);
            }
            this.InvokeAsync("getPodjetjeWithMaxOseb", new object[0], this.getPodjetjeWithMaxOsebOperationCompleted, userState);
        }
        
        private void OngetPodjetjeWithMaxOsebOperationCompleted(object arg) {
            if ((this.getPodjetjeWithMaxOsebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPodjetjeWithMaxOsebCompleted(this, new getPodjetjeWithMaxOsebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebaWithMaxPod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba getOsebaWithMaxPod() {
            object[] results = this.Invoke("getOsebaWithMaxPod", new object[0]);
            return ((Oseba)(results[0]));
        }
        
        /// <remarks/>
        public void getOsebaWithMaxPodAsync() {
            this.getOsebaWithMaxPodAsync(null);
        }
        
        /// <remarks/>
        public void getOsebaWithMaxPodAsync(object userState) {
            if ((this.getOsebaWithMaxPodOperationCompleted == null)) {
                this.getOsebaWithMaxPodOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebaWithMaxPodOperationCompleted);
            }
            this.InvokeAsync("getOsebaWithMaxPod", new object[0], this.getOsebaWithMaxPodOperationCompleted, userState);
        }
        
        private void OngetOsebaWithMaxPodOperationCompleted(object arg) {
            if ((this.getOsebaWithMaxPodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebaWithMaxPodCompleted(this, new getOsebaWithMaxPodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewOseba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertNewOseba(string ime, string priimek, int letoRojstva) {
            object[] results = this.Invoke("InsertNewOseba", new object[] {
                        ime,
                        priimek,
                        letoRojstva});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNewOsebaAsync(string ime, string priimek, int letoRojstva) {
            this.InsertNewOsebaAsync(ime, priimek, letoRojstva, null);
        }
        
        /// <remarks/>
        public void InsertNewOsebaAsync(string ime, string priimek, int letoRojstva, object userState) {
            if ((this.InsertNewOsebaOperationCompleted == null)) {
                this.InsertNewOsebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNewOsebaOperationCompleted);
            }
            this.InvokeAsync("InsertNewOseba", new object[] {
                        ime,
                        priimek,
                        letoRojstva}, this.InsertNewOsebaOperationCompleted, userState);
        }
        
        private void OnInsertNewOsebaOperationCompleted(object arg) {
            if ((this.InsertNewOsebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNewOsebaCompleted(this, new InsertNewOsebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewPodjetje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertNewPodjetje(string naziv, string panoga, int leto) {
            object[] results = this.Invoke("InsertNewPodjetje", new object[] {
                        naziv,
                        panoga,
                        leto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNewPodjetjeAsync(string naziv, string panoga, int leto) {
            this.InsertNewPodjetjeAsync(naziv, panoga, leto, null);
        }
        
        /// <remarks/>
        public void InsertNewPodjetjeAsync(string naziv, string panoga, int leto, object userState) {
            if ((this.InsertNewPodjetjeOperationCompleted == null)) {
                this.InsertNewPodjetjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNewPodjetjeOperationCompleted);
            }
            this.InvokeAsync("InsertNewPodjetje", new object[] {
                        naziv,
                        panoga,
                        leto}, this.InsertNewPodjetjeOperationCompleted, userState);
        }
        
        private void OnInsertNewPodjetjeOperationCompleted(object arg) {
            if ((this.InsertNewPodjetjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNewPodjetjeCompleted(this, new InsertNewPodjetjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertNewUser(string ime, string geslo, bool admin) {
            object[] results = this.Invoke("InsertNewUser", new object[] {
                        ime,
                        geslo,
                        admin});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNewUserAsync(string ime, string geslo, bool admin) {
            this.InsertNewUserAsync(ime, geslo, admin, null);
        }
        
        /// <remarks/>
        public void InsertNewUserAsync(string ime, string geslo, bool admin, object userState) {
            if ((this.InsertNewUserOperationCompleted == null)) {
                this.InsertNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNewUserOperationCompleted);
            }
            this.InvokeAsync("InsertNewUser", new object[] {
                        ime,
                        geslo,
                        admin}, this.InsertNewUserOperationCompleted, userState);
        }
        
        private void OnInsertNewUserOperationCompleted(object arg) {
            if ((this.InsertNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNewUserCompleted(this, new InsertNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveOseba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RemoveOseba(string ime, string priimek) {
            object[] results = this.Invoke("RemoveOseba", new object[] {
                        ime,
                        priimek});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveOsebaAsync(string ime, string priimek) {
            this.RemoveOsebaAsync(ime, priimek, null);
        }
        
        /// <remarks/>
        public void RemoveOsebaAsync(string ime, string priimek, object userState) {
            if ((this.RemoveOsebaOperationCompleted == null)) {
                this.RemoveOsebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveOsebaOperationCompleted);
            }
            this.InvokeAsync("RemoveOseba", new object[] {
                        ime,
                        priimek}, this.RemoveOsebaOperationCompleted, userState);
        }
        
        private void OnRemoveOsebaOperationCompleted(object arg) {
            if ((this.RemoveOsebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveOsebaCompleted(this, new RemoveOsebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemovePodjetje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RemovePodjetje(string naziv) {
            object[] results = this.Invoke("RemovePodjetje", new object[] {
                        naziv});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RemovePodjetjeAsync(string naziv) {
            this.RemovePodjetjeAsync(naziv, null);
        }
        
        /// <remarks/>
        public void RemovePodjetjeAsync(string naziv, object userState) {
            if ((this.RemovePodjetjeOperationCompleted == null)) {
                this.RemovePodjetjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemovePodjetjeOperationCompleted);
            }
            this.InvokeAsync("RemovePodjetje", new object[] {
                        naziv}, this.RemovePodjetjeOperationCompleted, userState);
        }
        
        private void OnRemovePodjetjeOperationCompleted(object arg) {
            if ((this.RemovePodjetjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemovePodjetjeCompleted(this, new RemovePodjetjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOsebaVPodjetje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOsebaVPodjetje(string ime, string priimek, string nazivPod, string delovnoMesto, int letoDo) {
            object[] results = this.Invoke("AddOsebaVPodjetje", new object[] {
                        ime,
                        priimek,
                        nazivPod,
                        delovnoMesto,
                        letoDo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOsebaVPodjetjeAsync(string ime, string priimek, string nazivPod, string delovnoMesto, int letoDo) {
            this.AddOsebaVPodjetjeAsync(ime, priimek, nazivPod, delovnoMesto, letoDo, null);
        }
        
        /// <remarks/>
        public void AddOsebaVPodjetjeAsync(string ime, string priimek, string nazivPod, string delovnoMesto, int letoDo, object userState) {
            if ((this.AddOsebaVPodjetjeOperationCompleted == null)) {
                this.AddOsebaVPodjetjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOsebaVPodjetjeOperationCompleted);
            }
            this.InvokeAsync("AddOsebaVPodjetje", new object[] {
                        ime,
                        priimek,
                        nazivPod,
                        delovnoMesto,
                        letoDo}, this.AddOsebaVPodjetjeOperationCompleted, userState);
        }
        
        private void OnAddOsebaVPodjetjeOperationCompleted(object arg) {
            if ((this.AddOsebaVPodjetjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOsebaVPodjetjeCompleted(this, new AddOsebaVPodjetjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveOsebeIzPodjetja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RemoveOsebeIzPodjetja(string ime, string priimek, string naziv) {
            object[] results = this.Invoke("RemoveOsebeIzPodjetja", new object[] {
                        ime,
                        priimek,
                        naziv});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveOsebeIzPodjetjaAsync(string ime, string priimek, string naziv) {
            this.RemoveOsebeIzPodjetjaAsync(ime, priimek, naziv, null);
        }
        
        /// <remarks/>
        public void RemoveOsebeIzPodjetjaAsync(string ime, string priimek, string naziv, object userState) {
            if ((this.RemoveOsebeIzPodjetjaOperationCompleted == null)) {
                this.RemoveOsebeIzPodjetjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveOsebeIzPodjetjaOperationCompleted);
            }
            this.InvokeAsync("RemoveOsebeIzPodjetja", new object[] {
                        ime,
                        priimek,
                        naziv}, this.RemoveOsebeIzPodjetjaOperationCompleted, userState);
        }
        
        private void OnRemoveOsebeIzPodjetjaOperationCompleted(object arg) {
            if ((this.RemoveOsebeIzPodjetjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveOsebeIzPodjetjaCompleted(this, new RemoveOsebeIzPodjetjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOsebe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateOsebe(string ime, string priimek, string newIme, string newPriimek, int newLeto) {
            object[] results = this.Invoke("UpdateOsebe", new object[] {
                        ime,
                        priimek,
                        newIme,
                        newPriimek,
                        newLeto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOsebeAsync(string ime, string priimek, string newIme, string newPriimek, int newLeto) {
            this.UpdateOsebeAsync(ime, priimek, newIme, newPriimek, newLeto, null);
        }
        
        /// <remarks/>
        public void UpdateOsebeAsync(string ime, string priimek, string newIme, string newPriimek, int newLeto, object userState) {
            if ((this.UpdateOsebeOperationCompleted == null)) {
                this.UpdateOsebeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOsebeOperationCompleted);
            }
            this.InvokeAsync("UpdateOsebe", new object[] {
                        ime,
                        priimek,
                        newIme,
                        newPriimek,
                        newLeto}, this.UpdateOsebeOperationCompleted, userState);
        }
        
        private void OnUpdateOsebeOperationCompleted(object arg) {
            if ((this.UpdateOsebeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOsebeCompleted(this, new UpdateOsebeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePodjetje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdatePodjetje(string naziv, string newNaziv, string newPanoga, int newLeto) {
            object[] results = this.Invoke("UpdatePodjetje", new object[] {
                        naziv,
                        newNaziv,
                        newPanoga,
                        newLeto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePodjetjeAsync(string naziv, string newNaziv, string newPanoga, int newLeto) {
            this.UpdatePodjetjeAsync(naziv, newNaziv, newPanoga, newLeto, null);
        }
        
        /// <remarks/>
        public void UpdatePodjetjeAsync(string naziv, string newNaziv, string newPanoga, int newLeto, object userState) {
            if ((this.UpdatePodjetjeOperationCompleted == null)) {
                this.UpdatePodjetjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePodjetjeOperationCompleted);
            }
            this.InvokeAsync("UpdatePodjetje", new object[] {
                        naziv,
                        newNaziv,
                        newPanoga,
                        newLeto}, this.UpdatePodjetjeOperationCompleted, userState);
        }
        
        private void OnUpdatePodjetjeOperationCompleted(object arg) {
            if ((this.UpdatePodjetjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePodjetjeCompleted(this, new UpdatePodjetjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OdstraniOsebo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OdstraniOsebo(int id) {
            object[] results = this.Invoke("OdstraniOsebo", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OdstraniOseboAsync(int id) {
            this.OdstraniOseboAsync(id, null);
        }
        
        /// <remarks/>
        public void OdstraniOseboAsync(int id, object userState) {
            if ((this.OdstraniOseboOperationCompleted == null)) {
                this.OdstraniOseboOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOdstraniOseboOperationCompleted);
            }
            this.InvokeAsync("OdstraniOsebo", new object[] {
                        id}, this.OdstraniOseboOperationCompleted, userState);
        }
        
        private void OnOdstraniOseboOperationCompleted(object arg) {
            if ((this.OdstraniOseboCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OdstraniOseboCompleted(this, new OdstraniOseboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OdstraniPodjetje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OdstraniPodjetje(int id) {
            object[] results = this.Invoke("OdstraniPodjetje", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OdstraniPodjetjeAsync(int id) {
            this.OdstraniPodjetjeAsync(id, null);
        }
        
        /// <remarks/>
        public void OdstraniPodjetjeAsync(int id, object userState) {
            if ((this.OdstraniPodjetjeOperationCompleted == null)) {
                this.OdstraniPodjetjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOdstraniPodjetjeOperationCompleted);
            }
            this.InvokeAsync("OdstraniPodjetje", new object[] {
                        id}, this.OdstraniPodjetjeOperationCompleted, userState);
        }
        
        private void OnOdstraniPodjetjeOperationCompleted(object arg) {
            if ((this.OdstraniPodjetjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OdstraniPodjetjeCompleted(this, new OdstraniPodjetjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OdstraniOseboIzPodjetjaByIndex", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OdstraniOseboIzPodjetjaByIndex(int indexOseba, int indexPodjetej) {
            object[] results = this.Invoke("OdstraniOseboIzPodjetjaByIndex", new object[] {
                        indexOseba,
                        indexPodjetej});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OdstraniOseboIzPodjetjaByIndexAsync(int indexOseba, int indexPodjetej) {
            this.OdstraniOseboIzPodjetjaByIndexAsync(indexOseba, indexPodjetej, null);
        }
        
        /// <remarks/>
        public void OdstraniOseboIzPodjetjaByIndexAsync(int indexOseba, int indexPodjetej, object userState) {
            if ((this.OdstraniOseboIzPodjetjaByIndexOperationCompleted == null)) {
                this.OdstraniOseboIzPodjetjaByIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOdstraniOseboIzPodjetjaByIndexOperationCompleted);
            }
            this.InvokeAsync("OdstraniOseboIzPodjetjaByIndex", new object[] {
                        indexOseba,
                        indexPodjetej}, this.OdstraniOseboIzPodjetjaByIndexOperationCompleted, userState);
        }
        
        private void OnOdstraniOseboIzPodjetjaByIndexOperationCompleted(object arg) {
            if ((this.OdstraniOseboIzPodjetjaByIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OdstraniOseboIzPodjetjaByIndexCompleted(this, new OdstraniOseboIzPodjetjaByIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOsebaVPodjetjeByIndex", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOsebaVPodjetjeByIndex(int indexO, int indexP, string delovnoMesto, int letoDo) {
            object[] results = this.Invoke("AddOsebaVPodjetjeByIndex", new object[] {
                        indexO,
                        indexP,
                        delovnoMesto,
                        letoDo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOsebaVPodjetjeByIndexAsync(int indexO, int indexP, string delovnoMesto, int letoDo) {
            this.AddOsebaVPodjetjeByIndexAsync(indexO, indexP, delovnoMesto, letoDo, null);
        }
        
        /// <remarks/>
        public void AddOsebaVPodjetjeByIndexAsync(int indexO, int indexP, string delovnoMesto, int letoDo, object userState) {
            if ((this.AddOsebaVPodjetjeByIndexOperationCompleted == null)) {
                this.AddOsebaVPodjetjeByIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOsebaVPodjetjeByIndexOperationCompleted);
            }
            this.InvokeAsync("AddOsebaVPodjetjeByIndex", new object[] {
                        indexO,
                        indexP,
                        delovnoMesto,
                        letoDo}, this.AddOsebaVPodjetjeByIndexOperationCompleted, userState);
        }
        
        private void OnAddOsebaVPodjetjeByIndexOperationCompleted(object arg) {
            if ((this.AddOsebaVPodjetjeByIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOsebaVPodjetjeByIndexCompleted(this, new AddOsebaVPodjetjeByIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OsebaVPodjetju {
        
        private int osebaVPodjetjuIdField;
        
        private int letoOdField;
        
        private int letoDoField;
        
        private string delovnoMestoField;
        
        private int osebaIdField;
        
        private int podjetjeIdField;
        
        private Oseba osebaField;
        
        private Podjetje podjetjeField;
        
        /// <remarks/>
        public int OsebaVPodjetjuId {
            get {
                return this.osebaVPodjetjuIdField;
            }
            set {
                this.osebaVPodjetjuIdField = value;
            }
        }
        
        /// <remarks/>
        public int letoOd {
            get {
                return this.letoOdField;
            }
            set {
                this.letoOdField = value;
            }
        }
        
        /// <remarks/>
        public int letoDo {
            get {
                return this.letoDoField;
            }
            set {
                this.letoDoField = value;
            }
        }
        
        /// <remarks/>
        public string delovnoMesto {
            get {
                return this.delovnoMestoField;
            }
            set {
                this.delovnoMestoField = value;
            }
        }
        
        /// <remarks/>
        public int OsebaId {
            get {
                return this.osebaIdField;
            }
            set {
                this.osebaIdField = value;
            }
        }
        
        /// <remarks/>
        public int PodjetjeId {
            get {
                return this.podjetjeIdField;
            }
            set {
                this.podjetjeIdField = value;
            }
        }
        
        /// <remarks/>
        public Oseba Oseba {
            get {
                return this.osebaField;
            }
            set {
                this.osebaField = value;
            }
        }
        
        /// <remarks/>
        public Podjetje Podjetje {
            get {
                return this.podjetjeField;
            }
            set {
                this.podjetjeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Oseba {
        
        private int osebaIdField;
        
        private string imeField;
        
        private string priimekField;
        
        private int letoRojstvaField;
        
        /// <remarks/>
        public int OsebaId {
            get {
                return this.osebaIdField;
            }
            set {
                this.osebaIdField = value;
            }
        }
        
        /// <remarks/>
        public string ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        public string priimek {
            get {
                return this.priimekField;
            }
            set {
                this.priimekField = value;
            }
        }
        
        /// <remarks/>
        public int letoRojstva {
            get {
                return this.letoRojstvaField;
            }
            set {
                this.letoRojstvaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Podjetje {
        
        private int podjetjeIdField;
        
        private string nazivField;
        
        private string panogaField;
        
        private int letoUstanovitveField;
        
        /// <remarks/>
        public int PodjetjeId {
            get {
                return this.podjetjeIdField;
            }
            set {
                this.podjetjeIdField = value;
            }
        }
        
        /// <remarks/>
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        public string panoga {
            get {
                return this.panogaField;
            }
            set {
                this.panogaField = value;
            }
        }
        
        /// <remarks/>
        public int letoUstanovitve {
            get {
                return this.letoUstanovitveField;
            }
            set {
                this.letoUstanovitveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getPodjetjeMaxCompletedEventHandler(object sender, getPodjetjeMaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPodjetjeMaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPodjetjeMaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OsebaVPodjetju Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OsebaVPodjetju)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebeVPodCompletedEventHandler(object sender, getOsebeVPodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebeVPodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebeVPodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebaImeCompletedEventHandler(object sender, getOsebaImeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebaImeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebaImeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void minOsebaCompletedEventHandler(object sender, minOsebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class minOsebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal minOsebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void listaOsebCompletedEventHandler(object sender, listaOsebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaOsebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaOsebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void listaPodjetjaCompletedEventHandler(object sender, listaPodjetjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaPodjetjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaPodjetjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Podjetje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Podjetje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void povprecnaCompletedEventHandler(object sender, povprecnaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class povprecnaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal povprecnaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebeAllCompletedEventHandler(object sender, getOsebeAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebeAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebeAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getPodjetjeAllCompletedEventHandler(object sender, getPodjetjeAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPodjetjeAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPodjetjeAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Podjetje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Podjetje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void isAdministratorCompletedEventHandler(object sender, isAdministratorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isAdministratorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isAdministratorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getPodjetjeWithMaxOsebCompletedEventHandler(object sender, getPodjetjeWithMaxOsebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPodjetjeWithMaxOsebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPodjetjeWithMaxOsebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Podjetje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Podjetje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebaWithMaxPodCompletedEventHandler(object sender, getOsebaWithMaxPodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebaWithMaxPodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebaWithMaxPodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertNewOsebaCompletedEventHandler(object sender, InsertNewOsebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNewOsebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNewOsebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertNewPodjetjeCompletedEventHandler(object sender, InsertNewPodjetjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNewPodjetjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNewPodjetjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertNewUserCompletedEventHandler(object sender, InsertNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveOsebaCompletedEventHandler(object sender, RemoveOsebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveOsebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveOsebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemovePodjetjeCompletedEventHandler(object sender, RemovePodjetjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemovePodjetjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemovePodjetjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddOsebaVPodjetjeCompletedEventHandler(object sender, AddOsebaVPodjetjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOsebaVPodjetjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOsebaVPodjetjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RemoveOsebeIzPodjetjaCompletedEventHandler(object sender, RemoveOsebeIzPodjetjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveOsebeIzPodjetjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveOsebeIzPodjetjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdateOsebeCompletedEventHandler(object sender, UpdateOsebeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOsebeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOsebeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdatePodjetjeCompletedEventHandler(object sender, UpdatePodjetjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePodjetjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePodjetjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OdstraniOseboCompletedEventHandler(object sender, OdstraniOseboCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OdstraniOseboCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OdstraniOseboCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OdstraniPodjetjeCompletedEventHandler(object sender, OdstraniPodjetjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OdstraniPodjetjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OdstraniPodjetjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OdstraniOseboIzPodjetjaByIndexCompletedEventHandler(object sender, OdstraniOseboIzPodjetjaByIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OdstraniOseboIzPodjetjaByIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OdstraniOseboIzPodjetjaByIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddOsebaVPodjetjeByIndexCompletedEventHandler(object sender, AddOsebaVPodjetjeByIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOsebaVPodjetjeByIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOsebaVPodjetjeByIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591