//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestApp.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOsebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebeVPodOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebaImeOperationCompleted;
        
        private System.Threading.SendOrPostCallback minOsebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaOsebOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaPodjetjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback povprecnaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOsebeAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPodjetjeAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback isAdministratorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPodatkiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::TestApp.Properties.Settings.Default.TestApp_localhost_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOsebaCompletedEventHandler getOsebaCompleted;
        
        /// <remarks/>
        public event getOsebeVPodCompletedEventHandler getOsebeVPodCompleted;
        
        /// <remarks/>
        public event getOsebaImeCompletedEventHandler getOsebaImeCompleted;
        
        /// <remarks/>
        public event minOsebaCompletedEventHandler minOsebaCompleted;
        
        /// <remarks/>
        public event listaOsebCompletedEventHandler listaOsebCompleted;
        
        /// <remarks/>
        public event listaPodjetjaCompletedEventHandler listaPodjetjaCompleted;
        
        /// <remarks/>
        public event povprecnaCompletedEventHandler povprecnaCompleted;
        
        /// <remarks/>
        public event getOsebeAllCompletedEventHandler getOsebeAllCompleted;
        
        /// <remarks/>
        public event getPodjetjeAllCompletedEventHandler getPodjetjeAllCompleted;
        
        /// <remarks/>
        public event isAdministratorCompletedEventHandler isAdministratorCompleted;
        
        /// <remarks/>
        public event SetPodatkiCompletedEventHandler SetPodatkiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOseba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getOseba() {
            object[] results = this.Invoke("getOseba", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOsebaAsync() {
            this.getOsebaAsync(null);
        }
        
        /// <remarks/>
        public void getOsebaAsync(object userState) {
            if ((this.getOsebaOperationCompleted == null)) {
                this.getOsebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebaOperationCompleted);
            }
            this.InvokeAsync("getOseba", new object[0], this.getOsebaOperationCompleted, userState);
        }
        
        private void OngetOsebaOperationCompleted(object arg) {
            if ((this.getOsebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebaCompleted(this, new getOsebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebeVPod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba[] getOsebeVPod() {
            object[] results = this.Invoke("getOsebeVPod", new object[0]);
            return ((Oseba[])(results[0]));
        }
        
        /// <remarks/>
        public void getOsebeVPodAsync() {
            this.getOsebeVPodAsync(null);
        }
        
        /// <remarks/>
        public void getOsebeVPodAsync(object userState) {
            if ((this.getOsebeVPodOperationCompleted == null)) {
                this.getOsebeVPodOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebeVPodOperationCompleted);
            }
            this.InvokeAsync("getOsebeVPod", new object[0], this.getOsebeVPodOperationCompleted, userState);
        }
        
        private void OngetOsebeVPodOperationCompleted(object arg) {
            if ((this.getOsebeVPodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebeVPodCompleted(this, new getOsebeVPodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebaIme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba getOsebaIme(string vnesenoIme) {
            object[] results = this.Invoke("getOsebaIme", new object[] {
                        vnesenoIme});
            return ((Oseba)(results[0]));
        }
        
        /// <remarks/>
        public void getOsebaImeAsync(string vnesenoIme) {
            this.getOsebaImeAsync(vnesenoIme, null);
        }
        
        /// <remarks/>
        public void getOsebaImeAsync(string vnesenoIme, object userState) {
            if ((this.getOsebaImeOperationCompleted == null)) {
                this.getOsebaImeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebaImeOperationCompleted);
            }
            this.InvokeAsync("getOsebaIme", new object[] {
                        vnesenoIme}, this.getOsebaImeOperationCompleted, userState);
        }
        
        private void OngetOsebaImeOperationCompleted(object arg) {
            if ((this.getOsebaImeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebaImeCompleted(this, new getOsebaImeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/minOseba", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba minOseba() {
            object[] results = this.Invoke("minOseba", new object[0]);
            return ((Oseba)(results[0]));
        }
        
        /// <remarks/>
        public void minOsebaAsync() {
            this.minOsebaAsync(null);
        }
        
        /// <remarks/>
        public void minOsebaAsync(object userState) {
            if ((this.minOsebaOperationCompleted == null)) {
                this.minOsebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnminOsebaOperationCompleted);
            }
            this.InvokeAsync("minOseba", new object[0], this.minOsebaOperationCompleted, userState);
        }
        
        private void OnminOsebaOperationCompleted(object arg) {
            if ((this.minOsebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.minOsebaCompleted(this, new minOsebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaOseb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OsebaVPodjetju[] listaOseb(string imePod) {
            object[] results = this.Invoke("listaOseb", new object[] {
                        imePod});
            return ((OsebaVPodjetju[])(results[0]));
        }
        
        /// <remarks/>
        public void listaOsebAsync(string imePod) {
            this.listaOsebAsync(imePod, null);
        }
        
        /// <remarks/>
        public void listaOsebAsync(string imePod, object userState) {
            if ((this.listaOsebOperationCompleted == null)) {
                this.listaOsebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaOsebOperationCompleted);
            }
            this.InvokeAsync("listaOseb", new object[] {
                        imePod}, this.listaOsebOperationCompleted, userState);
        }
        
        private void OnlistaOsebOperationCompleted(object arg) {
            if ((this.listaOsebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaOsebCompleted(this, new listaOsebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaPodjetja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OsebaVPodjetju[] listaPodjetja(string imeOsebe) {
            object[] results = this.Invoke("listaPodjetja", new object[] {
                        imeOsebe});
            return ((OsebaVPodjetju[])(results[0]));
        }
        
        /// <remarks/>
        public void listaPodjetjaAsync(string imeOsebe) {
            this.listaPodjetjaAsync(imeOsebe, null);
        }
        
        /// <remarks/>
        public void listaPodjetjaAsync(string imeOsebe, object userState) {
            if ((this.listaPodjetjaOperationCompleted == null)) {
                this.listaPodjetjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaPodjetjaOperationCompleted);
            }
            this.InvokeAsync("listaPodjetja", new object[] {
                        imeOsebe}, this.listaPodjetjaOperationCompleted, userState);
        }
        
        private void OnlistaPodjetjaOperationCompleted(object arg) {
            if ((this.listaPodjetjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaPodjetjaCompleted(this, new listaPodjetjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/povprecna", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string povprecna() {
            object[] results = this.Invoke("povprecna", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void povprecnaAsync() {
            this.povprecnaAsync(null);
        }
        
        /// <remarks/>
        public void povprecnaAsync(object userState) {
            if ((this.povprecnaOperationCompleted == null)) {
                this.povprecnaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpovprecnaOperationCompleted);
            }
            this.InvokeAsync("povprecna", new object[0], this.povprecnaOperationCompleted, userState);
        }
        
        private void OnpovprecnaOperationCompleted(object arg) {
            if ((this.povprecnaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.povprecnaCompleted(this, new povprecnaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOsebeAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Oseba[] getOsebeAll() {
            object[] results = this.Invoke("getOsebeAll", new object[0]);
            return ((Oseba[])(results[0]));
        }
        
        /// <remarks/>
        public void getOsebeAllAsync() {
            this.getOsebeAllAsync(null);
        }
        
        /// <remarks/>
        public void getOsebeAllAsync(object userState) {
            if ((this.getOsebeAllOperationCompleted == null)) {
                this.getOsebeAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOsebeAllOperationCompleted);
            }
            this.InvokeAsync("getOsebeAll", new object[0], this.getOsebeAllOperationCompleted, userState);
        }
        
        private void OngetOsebeAllOperationCompleted(object arg) {
            if ((this.getOsebeAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOsebeAllCompleted(this, new getOsebeAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPodjetjeAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Podjetje[] getPodjetjeAll() {
            object[] results = this.Invoke("getPodjetjeAll", new object[0]);
            return ((Podjetje[])(results[0]));
        }
        
        /// <remarks/>
        public void getPodjetjeAllAsync() {
            this.getPodjetjeAllAsync(null);
        }
        
        /// <remarks/>
        public void getPodjetjeAllAsync(object userState) {
            if ((this.getPodjetjeAllOperationCompleted == null)) {
                this.getPodjetjeAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPodjetjeAllOperationCompleted);
            }
            this.InvokeAsync("getPodjetjeAll", new object[0], this.getPodjetjeAllOperationCompleted, userState);
        }
        
        private void OngetPodjetjeAllOperationCompleted(object arg) {
            if ((this.getPodjetjeAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPodjetjeAllCompleted(this, new getPodjetjeAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isAdministrator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool isAdministrator(string rac, string geslo) {
            object[] results = this.Invoke("isAdministrator", new object[] {
                        rac,
                        geslo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isAdministratorAsync(string rac, string geslo) {
            this.isAdministratorAsync(rac, geslo, null);
        }
        
        /// <remarks/>
        public void isAdministratorAsync(string rac, string geslo, object userState) {
            if ((this.isAdministratorOperationCompleted == null)) {
                this.isAdministratorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisAdministratorOperationCompleted);
            }
            this.InvokeAsync("isAdministrator", new object[] {
                        rac,
                        geslo}, this.isAdministratorOperationCompleted, userState);
        }
        
        private void OnisAdministratorOperationCompleted(object arg) {
            if ((this.isAdministratorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isAdministratorCompleted(this, new isAdministratorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetPodatki", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetPodatki() {
            this.Invoke("SetPodatki", new object[0]);
        }
        
        /// <remarks/>
        public void SetPodatkiAsync() {
            this.SetPodatkiAsync(null);
        }
        
        /// <remarks/>
        public void SetPodatkiAsync(object userState) {
            if ((this.SetPodatkiOperationCompleted == null)) {
                this.SetPodatkiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPodatkiOperationCompleted);
            }
            this.InvokeAsync("SetPodatki", new object[0], this.SetPodatkiOperationCompleted, userState);
        }
        
        private void OnSetPodatkiOperationCompleted(object arg) {
            if ((this.SetPodatkiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPodatkiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Oseba {
        
        private string imeField;
        
        private string priimekField;
        
        private int letoRojstvaField;
        
        /// <remarks/>
        public string ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        public string priimek {
            get {
                return this.priimekField;
            }
            set {
                this.priimekField = value;
            }
        }
        
        /// <remarks/>
        public int letoRojstva {
            get {
                return this.letoRojstvaField;
            }
            set {
                this.letoRojstvaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Podjetje {
        
        private string nazivField;
        
        private string panogaField;
        
        private int letoUstanovitveField;
        
        /// <remarks/>
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        public string panoga {
            get {
                return this.panogaField;
            }
            set {
                this.panogaField = value;
            }
        }
        
        /// <remarks/>
        public int letoUstanovitve {
            get {
                return this.letoUstanovitveField;
            }
            set {
                this.letoUstanovitveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OsebaVPodjetju {
        
        private Oseba osebaField;
        
        private Podjetje podjetjeField;
        
        private int letoOdField;
        
        private int letoDoField;
        
        private string delovnoMestoField;
        
        /// <remarks/>
        public Oseba oseba {
            get {
                return this.osebaField;
            }
            set {
                this.osebaField = value;
            }
        }
        
        /// <remarks/>
        public Podjetje podjetje {
            get {
                return this.podjetjeField;
            }
            set {
                this.podjetjeField = value;
            }
        }
        
        /// <remarks/>
        public int letoOd {
            get {
                return this.letoOdField;
            }
            set {
                this.letoOdField = value;
            }
        }
        
        /// <remarks/>
        public int letoDo {
            get {
                return this.letoDoField;
            }
            set {
                this.letoDoField = value;
            }
        }
        
        /// <remarks/>
        public string delovnoMesto {
            get {
                return this.delovnoMestoField;
            }
            set {
                this.delovnoMestoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebaCompletedEventHandler(object sender, getOsebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebeVPodCompletedEventHandler(object sender, getOsebeVPodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebeVPodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebeVPodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebaImeCompletedEventHandler(object sender, getOsebaImeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebaImeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebaImeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void minOsebaCompletedEventHandler(object sender, minOsebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class minOsebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal minOsebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void listaOsebCompletedEventHandler(object sender, listaOsebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaOsebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaOsebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OsebaVPodjetju[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OsebaVPodjetju[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void listaPodjetjaCompletedEventHandler(object sender, listaPodjetjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaPodjetjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaPodjetjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OsebaVPodjetju[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OsebaVPodjetju[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void povprecnaCompletedEventHandler(object sender, povprecnaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class povprecnaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal povprecnaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getOsebeAllCompletedEventHandler(object sender, getOsebeAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOsebeAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOsebeAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Oseba[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Oseba[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getPodjetjeAllCompletedEventHandler(object sender, getPodjetjeAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPodjetjeAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPodjetjeAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Podjetje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Podjetje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void isAdministratorCompletedEventHandler(object sender, isAdministratorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isAdministratorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isAdministratorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SetPodatkiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591